version: "3.7"

services:
  gateway:
    image: ${REGISTRY}/cw-gateway-testing:${IMAGE_TAG}
    depends_on:
      - app-nginx
      - app-php-fpm
    ports:
    - "80:80"
  app-nginx:
    image: ${REGISTRY}/cw-app-nginx:${IMAGE_TAG}
    env_file:
      - .env.test
  app-php-fpm:
    env_file:
      - .env.test
    image: ${REGISTRY}/cw-app-php-fpm:${IMAGE_TAG}
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: commentwall
      MYSQL_USER: commentwall
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    command: --default-authentication-plugin=mysql_native_password --sql_mode=''
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
